---
- name: Enable automatic updates
  apt: pkg=unattended-upgrades state=present

- name: Copy unattended-upgrades configuration files in place.
  template: >
    src=../templates/{{ item }}.j2
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root group=root mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Install fail2ban
  apt: pkg=fail2ban state=present

- name: Disable password based SSH authentication
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
  notify: restart sshd
